require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'vov' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-admob', :path => '../node_modules/react-native-admob'

  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'RNFBAdMob', :path => '../node_modules/@react-native-firebase/admob'

  pod 'react-native-music-control', :path => '../node_modules/react-native-music-control'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  target 'vovTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'vov-tvOS' do
  # Pods for vov-tvOS

  target 'vov-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
